#!/bin/bash
set -e
DIR=$(dirname $0)
source $DIR/vars

cd $DIR/..
LOG=$(cat CHANGELOG  |grep "^  *" | head -n1 | sed "s/^  \* //" | \
    sed 's/\[/\\[/g; s/\]/\\]/g')
expect << EOF 
    spawn googlecode-upload.py -l "Featured" -s "$LOG" -p "$PROJECT" \
        -u "$USERNAME" "$FILE"
    expect "Password:"
    send "$PASSWORD\r"
    expect
EOF
