.TH "plowlist" "1" "March 15, 2010" "GPL" "Plowshare 0.9.2"

." ****************************************************************************
." * Name                                                                     *
." ****************************************************************************

.SH "NAME"
plowlist \- Command-line link-lister for file-sharing websites

." ****************************************************************************
." * Synopsis                                                                 *
." ****************************************************************************

.SH "SYNOPSIS"
.B plowdel
[OPTION]...
[MODULE_OPTION]...
URL...

." ****************************************************************************
." * Description                                                              *
." ****************************************************************************

.SH "DESCRIPTION"
.B plowdel
is a set of bash scripts designed for listing links (files) on file-sharing website.
Provided links can be downloaded with plowdown.

.TP 4
Currently supported hosting sites are:
mediafire.com

." ****************************************************************************
." * Options                                                                  *
." ****************************************************************************

.SH OPTIONS

.SS Logging options
.TP
.BI -v, " " --verbose "=LEVEL"
Set output verbose level:
.RS 
\fB0\fR  none,
.RE
.RS 
\fB1\fR  errors,
.RE
.RS
\fB2\fR  notice (default behavior),
.RE
.RS
\fB3\fR  debug.
.RE
.TP
.B -q, --quiet
Alias for \fB-v0\fR. Do not print any debug messages.
.SS Generic Program Information
.TP
.B -h, --help
Display this help and exit.
.TP
.B "   " --version
Output version information and exit.

." ****************************************************************************
." * Modules options                                                          *
." ****************************************************************************

.SH "MODULE OPTIONS"

None yet!

." ****************************************************************************
." * Examples                                                                 *
." ****************************************************************************

.SH EXAMPLES

.SS 1) list links one shared-folder page
.nf
$ plowlist http://www.mediafire.com/?sharekey=79ac821ea0110
.sp 1
# Deletes are successive (not parrallel)
$ plowlist http://www.mediafire.com/?sharekey=79ac821ea0110 http://www.mediafire.com/?sharekey=695c8c1ed055a
.fi

." ****************************************************************************
." * Authors / See Also / Copyright                                           *
." ****************************************************************************

.SH AUTHORS
Written by Arnau Sanchez and Matthieu Crapet.

.SH "SEE ALSO"
plowdown(1), plowup(1), plowdel(1)

.SH COPYRIGHT
Copyright (c) 2008\-2010 Plowshare Project.

This program is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published 
by the Free Software Foundation; either version 2 of the License, 
or (at your option) any later version.

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software 
Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
MA 02111-1307 USA.
